version: '3.5'
services:
  boat-systems-base:
    image: boat-systems-base
    build:
      context: base

  network-bridge:
    container_name: network-bridge
    image: network-bridge
    restart: always
    network_mode: host
    build:
      context: ../network/networkBridge
#    ports:
#      - "5000:5000/udp"
    volumes:
      - /tmp:/tmp
    depends_on:
      - boat-systems-base

  client:
    container_name: client
    image: client
    restart: always
    network_mode: host
    build:
      context: ../client
    ports:
    - "3000:3000"
    depends_on:
      - compass
      - autopilot

  http-bridge:
    container_name: http-bridge
    image: http-bridge
    restart: always
    network_mode: host
    build:
      context: ../network/httpBridge
    ports:
      - "3001:3001"
    volumes:
      - /tmp:/tmp
    depends_on:
      - compass
      - autopilot

  rudder:
    container_name: rudder
    image: rudder
    restart: always
    build:
      context: ../hardware/rudderInterface
    devices:
      - /dev/i2c-1
    volumes:
      - /tmp:/tmp
    depends_on:
      - boat-systems-base

  compass:
    container_name: compass
    image: compass
    restart: always
    build:
      context: ../hardware/compass
    devices:
      - /dev/i2c-1
    volumes:
    - /tmp:/tmp
    depends_on:
      - boat-systems-base

  autopilot:
    container_name: autopilot
    image: autopilot
    restart: always
    build:
      context: ../autopilot
    volumes:
    - /tmp:/tmp
    depends_on:
      - compass
      - rudder

