version: '3.5'
services:
  boat-systems-base:
    image: boat-systems-base
    build:
      context: base

  network-bridge:
    container_name: network-bridge
    image: network-bridge
    build:
      context: ../network/networkBridge
    expose:
      - "5000/udp"
    volumes:
      - /tmp:/tmp
    depends_on:
      - boat-systems-base

  client:
    container_name: client
    image: client
    build:
      context: ../client
    ports:
    - "3000:3000"
    depends_on:
      - compass
      - autopilot

  http-bridge:
    container_name: http-bridge
    image: http-bridge
    build:
      context: ../network/httpBridge
    ports:
      - "3001:3001"
    volumes:
      - /tmp:/tmp
    depends_on:
      - compass
      - autopilot

  compass:
    container_name: compass
    image: compass
    build:
      context: ../hardware/compass
    devices:
      - /dev/i2c-1
    volumes:
    - /tmp:/tmp
    depends_on:
      - boat-systems-base

  autopilot:
    container_name: autopilot
    image: autopilot
    build:
      context: ../autopilot
    volumes:
    - /tmp:/tmp
    depends_on:
      - compass

